# Generated by Django 4.2.5 on 2023-09-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_movel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('sobrenome', models.CharField(max_length=256)),
                ('telefone', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256)),
                ('duracao', models.PositiveIntegerField()),
                ('ano_lancamento', models.PositiveIntegerField()),
            ],
        ),
    ]
